import os
os.environ["SUPABASE_URL"] = "https://hjzghinbochdgozyqaoy.supabase.co"
os.environ["SUPABASE_SECRET_KEY"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqemdoaW5ib2NoZGdvenlxYW95Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzE5NjQ4NywiZXhwIjoyMTAyNzcyNDg3fQ.gyzHeIHIOtmdxT57oMYG44HXvxJUvIvZMu4cp3f5JRg"

from supabase import create_client

supabase = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SECRET_KEY"])
folder_id = "bbda898a-ab1b-48f5-a324-1f55cf73f187"

folder = supabase.table("folders").select("*").eq("id", folder_id).single().execute()
groups = supabase.table("question_groups").select("canonical_text, occurrence_count, avg_marks, priority_level, priority_score").eq("folder_id", folder_id).order("priority_score", desc=True).execute()

# 1. MARKDOWN
md = f"""# {folder.data['name']}

**Subject:** {folder.data['subject']}
**Exam Type:** {folder.data['exam_type']}
**Reference Year:** {folder.data['reference_year']}

---

## Questions by Priority

"""
for g in groups.data:
    md += f"### {g['canonical_text']}\n"
    md += f"- Repeated: {g['occurrence_count']}x\n"
    md += f"- Avg Marks: {g['avg_marks'] or 'N/A'}\n"
    md += f"- Priority: {g['priority_level']} (score: {g['priority_score']:.1f})\n\n"

md += f"\n---\n*Generated on 2026-08-21*\n"

with open("exports/OS_E2E_Flow_Test.md", "w", encoding="utf-8") as f:
    f.write(md)
print("✅ Markdown exported")

# 2. LATEX
latex = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\title{""" + folder.data['name'] + r"""}
\author{PaperLens Study Guide}
\date{2026-08-21}
\begin{document}
\maketitle
\section*{Exam Information}
Subject: """ + folder.data['subject'] + r"""

"""
latex += r"\section{Questions}" + "\n"
for i, g in enumerate(groups.data, 1):
    text = g['canonical_text'].replace('&', r'\&').replace('%', r'\%').replace('$', r'\$')
    latex += f"{i}. \\textbf{{{text}}}\\\\\n"
    latex += f"Repeated {g['occurrence_count']}$\\times$, Priority: {g['priority_level']}\n\n"

latex += r"\end{document}"

with open("exports/OS_E2E_Flow_Test.tex", "w", encoding="utf-8") as f:
    f.write(latex)
print("✅ LaTeX exported")

# 3. ANKI CSV
csv = "Front,Back,Tags\n"
for g in groups.data:
    front = g["canonical_text"].replace('"', '""')
    back = f"Repeated {g['occurrence_count']}x | Avg {g['avg_marks'] or 'N/A'} marks | Priority: {g['priority_level']}"
    tags = f"{folder.data['subject']}_{g['priority_level']}"
    csv += f'"{front}","{back}",{tags}\n'

with open("exports/OS_E2E_Flow_Test_anki.csv", "w", encoding="utf-8") as f:
    f.write(csv)
print("✅ Anki CSV exported")

# 4. PRINTABLE HTML
html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{folder.data['name']}</title>
<style>
body {{ font-family: 'Times New Roman', serif; margin: 40px; }}
h1 {{ text-align: center; border-bottom: 3px solid #333; padding-bottom: 10px; }}
.question {{ margin: 20px 0; page-break-inside: avoid; }}
.question-text {{ font-weight: bold; font-size: 1.1em; }}
.meta {{ color: #666; margin-left: 20px; font-size: 0.9em; }}
</style>
</head>
<body>
<h1>{folder.data['name']}</h1>
<p style="text-align:center;"><strong>Subject:</strong> {folder.data['subject']} | <strong>Year:</strong> {folder.data['reference_year']}</p>
<hr>
"""
for i, g in enumerate(groups.data, 1):
    html += f'<div class="question">'
    html += f'<div class="question-text">{i}. {g["canonical_text"]}</div>'
    html += f'<div class="meta">Repeated {g["occurrence_count"]}× | Avg {g["avg_marks"] or "N/A"} marks | Priority: {g["priority_level"]} ({g["priority_score"]:.1f})</div>'
    html += f'</div>'

html += f'<hr><p style="text-align:center; color:#999; font-size:0.8em;">Generated by PaperLens on 2026-08-21</p></body></html>'

with open("exports/OS_E2E_Flow_Test.html", "w", encoding="utf-8") as f:
    f.write(html)
print("✅ Printable HTML exported")

print("\nAll 4 formats generated in exports/ directory")
